import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  header: {
    height: hp(7),
    backgroundColor: '#FFDE4D',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(5),
    flexDirection: 'row',
  },
  back: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // borderWidth:1,
    width: wp(38),
    alignItems: 'center',
  },
  delebtn: {
    backgroundColor: '#ededed',
    height: wp(8),
    width: wp(15),
    marginRight: 10,
  },
  card: {
    // borderWidth:1,
    width: wp(32),
    height: hp(20),
    margin: wp(0.5),
    borderRadius: wp(3),
    backgroundColor: '#e6f0f2',
  },
  progressBarContainer: {
    width: '100%',
    height: 20,
    backgroundColor: '#e6f0f2',
    borderRadius: 10,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: 'green',
  },
  item: {
    // borderWidth:1,
    height: hp(6),
    paddingHorizontal: wp(5),
    backgroundColor: '#e6f0f2',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f2f5f4',
  },
  cardCont: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: wp(50),
    backgroundColor: '#e6f0f2',
  },
  listContainer: {
    height: hp(20),
    borderRadius:wp(2),
    elevation:2,
    backgroundColor: '#ffffff',
    marginVertical: wp(1),
    paddingHorizontal: wp(3),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  imgContainer: {
    height: '75%',
    width: '35%',
    resizeMode:'contain',
  },
  img: {
    height: '100%',
    width: '100%',
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    marginVertical: 10,
  },
  btn3: {
    marginTop: 10,
    borderColor: 'grey',
    //borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(2),
    alignSelf: 'flex-end',
    backgroundColor: '#FFDE4D',
  },
  itemContainer: {
    // marginLeft:'5%',
    // borderWidth:1,
    width: '55%',
    height: '100%',
    marginLeft: '7%',
    justifyContent: 'center',
  },
  Qnt: {
    height: hp(3),
    width: wp(15),
    backgroundColor: 'lightgrey',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '2%',
  },
  placeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  btn: {
    height: hp(5.5),
    width: wp(95),
    backgroundColor: '#FFDE4D',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(1),
  },
  btnText: {
    fontSize: wp(4),
    fontWeight: '500',
    color: 'white',
  },
  container: {
    flex: 1,
    backgroundColor: '#FCE7C8',
  },
  header: {
    height: hp(7),
    backgroundColor: '#FFDE4D',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(3),
    // shadowColor: 'black',
    // shadowOffset: {width: -2, height: 4},
    // shadowOpacity: 1,
    // shadowRadius: 3,
    // elevation: 2,
  },
  txt: {
    marginLeft:wp(3),
    width:'80%',
    fontSize: wp(5),
    color: '#000000',
  },
  content: {
    padding: wp('5%'),
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: hp('1%'),
    borderBottomWidth: 1,
    borderColor: '#ddd',
    paddingBottom: hp('1%'),
  },
  label: {
    fontSize: wp('4%'),
    color: '#333',
    fontWeight: '600',
  },
  value: {
    fontSize: wp('4%'),
    color: '#666',
  },
});
