import {Dimensions, StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  container: {
    height: hp(8),
    width: wp(100),
    alignItems: 'center',
    //justifyContent:'center',
    backgroundColor: '#e6f0f2',
    // borderWidth:1
    flexDirection: 'row',
    justifyContent: 'space-between',
    elevation: 1,
  },
  txt: {
    fontSize: wp(4),
    color: 'grey',
    paddingHorizontal: wp(3),
  },
  header: {
    height: hp(6),
    width: wp(100),
    backgroundColor: '#FFDE4D',
    alignItems: 'center',

    paddingHorizontal: wp(5),
    flexDirection: 'row',
  },
  back: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // borderWidth:1,
    width: wp(30),
    alignItems: 'center',
  },
  containerr: {
    height: hp(20),
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  // details: {
  //   flex: 1,
  //   backgroundColor: '#ffffff',
  //   marginTop: wp(5),
  //   borderRadius:wp(12),
  //   height: hp(150),
  //   width: wp(96),
  //   elevation: 2,
  //   marginHorizontal:wp(2),
  //   paddingBottom: hp(-10),
  // },
  details: {
    flex: 1,
    backgroundColor: '#ffffff',
    marginTop: wp(5),
    borderRadius: wp(12),
    width: wp(96),
    elevation: 2,
    marginHorizontal: wp(2),
    paddingBottom: hp(2), // Card ke andar spacing ke liye
    paddingTop: hp(2), // Upar se spacing ke liye
    // paddingHorizontal: wp(1), // Horizontal padding
    minHeight: hp(10), // Minimum height jab content kam ho
    flexGrow: 1, // Content ke hisaab se expand karne ke liye
  },
  
  inputcontainer: {
    height: 55,
    borderRadius: 5,
    marginTop: 10,
    flexDirection: 'row',
    paddingHorizontal: 15,
    borderWidth: 0.5,
  },
  inputcontainerr: {
    height: 55,
    width: wp(50),
    borderRadius: 5,
    marginTop: 10,
    flexDirection: 'row',
    paddingHorizontal: 15,
    borderWidth: 0.5,
    backgroundColor: 'grey',
  },
  quantity: {
    height: hp(4),
    width: hp(4),
    alignItems: 'center',
    // borderWidth: 1,
    justifyContent: 'center',
    backgroundColor: '#e6f0f2',
    borderRadius: wp(1),
  },
  checkboxContainer: {
    flexDirection: 'row',
    height: hp(4),
  },
  checkbox: {
    height: hp(10),
    width: wp(8),
  },
  label: {
    margin: 8,
  },
  prDeta: {
    width: wp(35),
    left: wp(1),
    borderRadius: wp(8),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    backgroundColor: 'white',
    borderColor: 'lightgrey',
    alignItems: 'center',
    justifyContent: 'center',
  },
  count: {
    //  borderWidth: 1,
    right: wp(6),
    height: hp(4),
    width: wp(30),
    paddingHorizontal: wp(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cont: {
    flexDirection: 'row',
    width: '100%',
    // top: wp(1),
    //borderWidth: 1,
    justifyContent: 'space-between',
  },
  plus: {
    height: hp(3.6),
    width: hp(3.6),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 3,
    backgroundColor: 'white',
    borderColor: 'lightgrey',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: wp(0.1),
    borderRadius: wp(2),
  },
  ratting: {
    // borderWidth:1,
    top: wp(5),
    width: wp(90),
    left: wp(5),
    alignItems: 'center',
    justifyContent: 'space-between',

    flexDirection: 'row',
  },
  name: {
    height: hp(10),
    marginTop: 10,

    borderRadius: wp(8),
    shadowColor: 'lightgrey',
    shadowOffset: {width: 2, height: 4},
    shadowOpacity: 0.1,

    shadowRadius: 3,
    backgroundColor: 'white',
    borderColor: 'lightgrey',
    alignItems: 'center',
    justifyContent: 'center',
  },
  description: {
    backgroundColor: '#ffffff',
    marginTop: hp(2),
    borderRadius: wp(12),
    fontSize: wp(20),
   
  },
  btn: {
    borderWidth: 1,
    top: wp(22),
    width: wp(34),
    left: wp(5),
    height: hp(4.7),
    borderRadius: wp(3),
    backgroundColor: '#FFDE4D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn3: {
    borderColor: 'grey',
    //borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(2),
    backgroundColor: '#FFDE4D',
  },
  specification: {
    width: wp(90),
    alignSelf: 'center',
    // borderWidth:1,
    top: hp(5),
    height: hp(5.8),
    borderRadius: wp(2),
    backgroundColor: '#f2f5f4',
    paddingHorizontal: wp(5),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  myStarStyle: {
    color: 'gold',
    backgroundColor: 'transparent',
    textShadowColor: 'black',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 2,
    fontSize: wp(5.5),
  },
  myEmptyStarStyle: {
    color: '#000',
  },
  container1: {
    padding: 5,
  },
  contentText1: {
    fontSize: 13,
    lineHeight: 24, 
    color: 'black',
  },
  toggleText1: {
    color: '#FFDE4D',
    fontSize: 14,
    fontFamily:'Mulish-Bold',
    marginLeft: hp(1), 
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  fullImage: {
    width: Dimensions.get('window').width, 
    height: Dimensions.get('window').height, 
  },
  closeButton1: {
    position: 'absolute',
    top: 0,

    // right: 10,
    zIndex: 1,
    width: '100%',
    height: hp(5),
    paddingHorizontal: wp(5),
    backgroundColor: '#FFDE4D',
  },
  closeIcon: {
    width: 30, // Close icon width
    height: 30, // Close icon height
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '98%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 10,
    // alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 5,
    right: 10,
    height: hp(5),
    width: wp(8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    marginTop: hp(3),
  },
});
