import {StyleSheet} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
export default StyleSheet.create({
  
  headerContainer: {
    marginTop: '3%',
    width: '95%',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  profilePick: {
    backgroundColor: 'white',
    height: hp('6%'),
    width: hp('6%'),
    borderRadius: hp('6%'),
    overflow: 'hidden',
  },
  icon: {
    fontSize: hp('5%'),
    color: '#FFDE4D',
    alignSelf: 'center',
  },
  input: {
    height: hp('7.5%'),
    marginBottom: hp('2%'),
    marginHorizontal: wp('5%'),
    backgroundColor: 'white',
    flexDirection: 'row',
    borderRadius: hp('.5%'),
    flexDirection: 'row',
    borderWidth: 0.5,
    borderColor: 'lightgrey',
    elevation: 1,
    marginTop: '2%',
  },
  picker: {
    width: '17%',
    backgroundColor: '#FFDE4D',
    borderRadius: hp('.50%'),
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    margin: '.50%',
  },
  photos: {
    height: hp('30%'),
    width: wp('100%'),
    marginTop: hp(2.5),
    // alignItems:'center',
    //justifyContent: 'center',
    // backgroundColor:'#e6f0f2',
    //borderWidth:1
  },
  con: {
    alignItems: 'center',
    // flexDirection:'row',
    width: '100%',
    // borderWidth: 1,
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    // backgroundColor:'white'
  },
  viewcontainer: {
    backgroundColor: '#333',
    height: hp('10%'),
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    // borderWidth:1
  },
  cicle: {
    height: hp('5%'),
    width: hp('5%'),
    borderRadius: hp('6%'),
    borderWidth: 1,
    borderColor: 'white',
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: 'rgba(13, 82, 214, 1)',
  },
  historyContainer: {
    margin: '2%',
    width: '20%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  txt: {
    fontSize: wp(2),
    color: 'white',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  category: {
    fontSize: wp(5),
   fontFamily:'Mulish-Bold',
    color: '#18314F',
  },
  categoryContainer: {
    height: hp('16%'),
    width: wp('30%'),
    borderRadius: hp('.50%'),
    overflow: 'hidden',
  },
  txtContainer: {
    height: hp(2.5),
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(25),
  },
  titleContainer: {
    
    paddingHorizontal:10,
    padding:wp(1),
    width: wp(100),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: hp(5),
    backgroundColor: '#FCE7C8',
    
  },
  titleContainer1: {
    marginTop:wp(-10),
    // borderWidth:1,
    paddingHorizontal:10,
    padding:wp(1),
    width: wp(100),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: hp(10),
    backgroundColor: '#FCE7C8',
  },
  text: {
    alignSelf: 'center',
    color: 'black',
    fontSize: wp(3),
  },
  ViewContainer: {
    height: '85%',
    width: '58%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  image: {
    height: '100%',
    width: '100%',
    resizeMode: 'contain',
    borderRadius: 10,
  },
  img2: {
    height: '100%',
    width: '97%',
    alignSelf: 'center',
  },
  btn: {
    height: '15%',
    width: '28%',
    marginLeft: '-45%',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    backgroundColor: '#FFDE4D',
  },
  cardView: {
    // borderWidth:1,
    paddingHorizontal:wp(1),
    backgroundColor: '#ffffff',
    marginVertical: wp(1),
    width: wp(47.2),
    marginLeft:wp(1.5),
    marginHorizontal: wp(1),
    borderRadius: wp(2),
    shadowColor: 'black',
    shadowOpacity: 0.05,
  },
  cardsView: {
    height: hp('20%'),
    backgroundColor: '#ffffff',
    width: wp(35),
    marginHorizontal: wp(1),
    borderRadius: wp(2),
  },
  
  CardContainer: {
    flex: 1,
    
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: wp(1),
    marginHorizontal: wp(2),
  },
  imgcontainer: {
    height: wp(40),
    width: '100%',
  },
  imagecontainer: {
    height: wp(20),
    width: wp(30),
    alignSelf: 'center',
    margin: 10,
  },
  img: {
    height: '100%',
    width: '100%',
    borderTopLeftRadius: wp(2),
    borderTopRightRadius: wp(2),
    resizeMode:'contain'
  },
  images: {
    height: '100%',
    width: '100%',
    resizeMode:'contain'
  },
  txt2: {
    alignSelf: 'center',
    marginTop: wp(2),
    fontSize: wp(3.5),
  fontFamily:"Mulish-SemiBold",
    color: 'black',
  },
  txt3: {
    // borderWidth:1,
    padding:wp(1),
    marginTop: wp(2),
    fontSize: wp(3.5),
    fontFamily:"Mulish-SemiBold",
    color: 'black',
  },
  btn: {
    borderRadius: wp(1),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    width: wp(22),
    height: hp(3.5),
    borderColor: 'grey',
    alignSelf: 'center',
    marginTop: hp(3),
    backgroundColor: '#FFDE4D',
  },
  priceCOntainer: {
    // marginTop: hp(1),
    marginBottom: hp(1),
    padding: wp(1),
  },
  Price: {
    fontSize: wp(5),
    padding:wp(1),
    fontFamily:"Mulish-Bold",
    color: 'black',
  },
  searchContainer: {
    backgroundColor: 'white',
  },
  searchBarContainer: {
    backgroundColor: 'white',
    borderBottomColor: 'white',
    borderTopColor: 'white',
  },
  searchBarInputContainer: {
    backgroundColor: 'white',
  },
  icon2: {
    fontSize: wp(7),
    position: 'absolute',
    top: -hp('69%'),
  },
  iconic: {
    fontSize: wp(7),
    position: 'absolute',
  },
  container: {
    paddingHorizontal: 10,
    marginTop: 10,
    flex: 1,
    alignItems: "center",
  },
  slide: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    // overflow: "hidden",
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: 'contain',
    borderRadius: 10,
  },
  paginationContainer: {
  
    alignSelf: "center",
  },
  activeDot: {
    width: 25,
    height: 8,
    borderRadius: 6,
    backgroundColor: "#FFDE4D",
    marginHorizontal: -3,
  },
  inactiveDot: {
    width: 15,
    height: 15,
    borderRadius: 7,
    backgroundColor: "#7d7d7d",
    marginHorizontal: -3,
  },
});
