import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

export default StyleSheet.create({
  header: {
    height: hp(7),
    backgroundColor: '#FFDE4D',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: wp(3),
    shadowColor: 'black',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 1,
    shadowRadius: 3,
    elevation: 2,
  },
  txt: {
    fontSize: wp(4.5), color: '#000000',
    marginLeft:wp(5),
    fontFamily:'Mulish-Bold'
  },
  container1: {
    marginVertical: hp(3),
    width: '100%',
    paddingHorizontal: wp(3),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    
  },
  img: {
    // borderWidth:1,
    height: hp(10),
    width: hp(10),
    flexDirection:'row',
    
  },
  cat: {
    backgroundColor: 'white',
    marginHorizontal: wp(1),
    height: '65%',
    alignSelf: 'center',
    alignItems: 'center',
    // justifyContent:'center',
    paddingHorizontal: wp(2),
    borderRadius: wp(3),
    borderWidth: wp(0.1),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  nameContainer: {
    height: hp(5),
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(3),
    flexDirection: 'row',
    paddingRight: wp(7),
    marginTop: wp(2),
  },
  cardContainer: {
    paddingHorizontal: wp(3),
    marginVertical: hp(4),
    justifyContent: 'space-between',
    // height: hp(6),
  },
  touchBtn: {
    borderWidth: wp(0.2),
    borderColor: 'grey',
    width: wp(45),
    height: hp(5),
    borderRadius: wp(2),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: wp(3),
    paddingRight: wp(2),
    backgroundColor: '#f2f5f4',
  },
  listContainer: {
    borderTopWidth: wp(0.2),
    borderColor: 'grey',
    //marginTop:wp(3),
    paddingVertical: wp(2),
    backgroundColor: '#ffffff',
    paddingHorizontal: wp(2),
    //alignItems:'center',
    // justifyContent: 'space-between',
    //flexDirection: 'row',
  },
  btn: {
    // marginVertical: hp(3),
    height: hp(6),
    width: wp(85),
    alignSelf: 'center',
    borderWidth: wp(0.3),
    borderColor: '#FFDE4D',
    backgroundColor:'#FFDE4D',
    borderRadius: wp(2),
    alignItems: 'center',
    justifyContent: 'center',
    marginTop:hp(3)
  },
  HideView: {
    paddingVertical: wp(3),
    //: 'center',
   width:'60%',
   flexDirection:'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: wp(3),
  },
  btn2: {
    borderWidth: wp(0.08),
    height: hp(10),
    width: wp(28),
    borderRadius: wp(3),
    borderColor: 'grey',
    alignItems: 'center',
    justifyContent: 'center',
  },

  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    backgroundColor: 'white',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
  },
  closeButton: {
    position: 'absolute',
    top: 5,
    right: 10,
    height: hp(5),
    width: wp(8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,marginTop:hp(3)
  },
  input: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 5,
    padding: 10,
    marginVertical: 10,
  },
  submitButton: {
    backgroundColor: '#FFDE4D',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    marginTop: 15,
  },
  submitButtonText: {
    color: 'white',
    fontSize: 16,
  },
  
});
